name = "BPPLib"
uuid = "4cecd8e0-2093-46a9-836b-e2148d4f1997"
authors = ["Rafael Martinelli"]
version = "0.1.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
